### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by Quaerere-Git** [TeamNED/GregTech6-Translation-Groupware#2]
如图（流体处被错译为酸牛奶，实际为豆奶）
![2022-08-27_18 11 40](https://user-images.githubusercontent.com/42565872/187025757-70d67b84-5b71-4bd2-953f-37940a828a8e.png)
![2022-08-27_18 11 44](https://user-images.githubusercontent.com/42565872/187025758-273634f8-e2a3-4d48-a80a-5c3d131e8e15.png)

**Comment by Tanimodori** [comment]
按照MC百科词条，已将错译“酸牛奶”，别名“豆奶”统一为“豆浆”。
