### ISSUE TITLE
mistranslating materials

### ISSUE THREAD

**Issue by kuzuanpa** [TeamNED/GregTech6-Translation-Groupware#6]
材料"Mercury"制成的各种物品（杆、锭等）应被翻译为"汞"而非"水星"
（material里的是对的，oredict项的错了）
矿石"Lazurite"不应译成"天青石",天青石是另一种完全不同的矿物，主要含硫、锶、钡，而lazurite是一种青金石，在gt6中与青金石具有类似的成分，只是颜色不同，建议译为"浅色青金石"、"天蓝青金石"（仅供参考）等

**Comment by Tanimodori** [comment]
Lazurite应该是GT5中的同名矿物，其翻译为“蓝金石”（参见 https://www.mcmod.cn/item/57207.html ），不过该翻译疑似为原创矿石翻译，实际上并未得到广泛认可。个人觉得“天蓝青金石”更好。

**Comment by Tanimodori** [comment]
fixed in release https://github.com/TeamNED/GregTech6-Translation-Groupware/releases/tag/6.15.10-alpha

**Comment by Mobius0526** [comment]
Mercury很可能是我的锅，我给水星石头注册了材料，我参照月岩含moon，我就让水星石头含Mercury了
