### ISSUE TITLE
Update to GregTech ^6.16.00

### ISSUE THREAD

**Issue by kuzuanpa** [TeamNED/GregTech6-Translation-Groupware#9]
https://forum.mechaenetia.com/t/after-updating-the-latest-version-the-localization-file-will-become-invalid/2773/2

**Comment by byeLihua** [comment]
### gregtech6.16.00有更改
以下摘自gregtech6.16.00的changelog
>  [IMPORTANT] I removed ".name" from pretty much all Lang File Entries, because it was absolutely redundant and caused duplicate Entries at times. A simple Search&Replace with ".name=" and "=" BEFORE loading Minecraft, should fix it.

**Comment by LonelySteve** [comment]
这个问题应该尽快修复下，不然像我这种刚入坑的萌新，用最新版GT6装了翻译文件却完全不知道为啥不生效，在作者修复之前，我简单处理了下最新发布的语言文件，可以到我的仓库下载：

https://github.com/LonelySteve/GregTech6-Translation-Lang

还有 issues 的标题建议改一下并且 Pin 起来，这还是挺重要的问题。

**Comment by Tanimodori** [comment]
Partial translation of 6.16.02 was [released](https://github.com/TeamNED/GregTech6-Translation-Groupware/releases/tag/6.16.02-alpha). Note that contents of books are not translated yet.
